// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reciplex.Server.Database;

#nullable disable

namespace Reciplex.Server.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Reciplex.Server.Database.DbObjects.AdditionalBookUserAccessDbObject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyTag")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastModified")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MayEditBook")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MayViewBook")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RecipeBookFk")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Reviewed")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserFk")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecipeBookFk");

                    b.HasIndex("UserFk");

                    b.HasIndex("UserFk", "RecipeBookFk")
                        .IsUnique();

                    b.ToTable("RecipeBookAccessEntries");
                });

            modelBuilder.Entity("Reciplex.Server.Database.DbObjects.RecipeBookDbObject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyTag")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastModified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("OwnerFk")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShareKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Deleted");

                    b.HasIndex("OwnerFk");

                    b.ToTable("RecipeBooks");
                });

            modelBuilder.Entity("Reciplex.Server.Database.DbObjects.RecipeDbObject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyTag")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(1048576)
                        .HasColumnType("TEXT");

                    b.Property<long>("LastModified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("RecipeBookFk")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Deleted");

                    b.HasIndex("RecipeBookFk");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("Reciplex.Server.Database.DbObjects.UserDbObject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Authority")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyTag")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("LastModified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Authority", "Subject");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Reciplex.Server.Database.DbObjects.AdditionalBookUserAccessDbObject", b =>
                {
                    b.HasOne("Reciplex.Server.Database.DbObjects.RecipeBookDbObject", "RecipeBook")
                        .WithMany("AdditionalUsers")
                        .HasForeignKey("RecipeBookFk")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Reciplex.Server.Database.DbObjects.UserDbObject", "User")
                        .WithMany("RecipeBookAccessEntities")
                        .HasForeignKey("UserFk")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RecipeBook");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Reciplex.Server.Database.DbObjects.RecipeBookDbObject", b =>
                {
                    b.HasOne("Reciplex.Server.Database.DbObjects.UserDbObject", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerFk")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Reciplex.Server.Database.DbObjects.RecipeDbObject", b =>
                {
                    b.HasOne("Reciplex.Server.Database.DbObjects.RecipeBookDbObject", "RecipeBook")
                        .WithMany("Recipes")
                        .HasForeignKey("RecipeBookFk")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RecipeBook");
                });

            modelBuilder.Entity("Reciplex.Server.Database.DbObjects.RecipeBookDbObject", b =>
                {
                    b.Navigation("AdditionalUsers");

                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("Reciplex.Server.Database.DbObjects.UserDbObject", b =>
                {
                    b.Navigation("RecipeBookAccessEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
