<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Reciplex.Server.Database\Reciplex.Server.Database.csproj" />
    <ProjectReference Include="..\Reciplex.Server.UserServices\Reciplex.Server.UserServices.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NodaTime" />
  </ItemGroup>
</Project>
